
"""
Description (What this script does):
This script parses the 'DomesticDeclarations.xes' event log using PM4Py to conduct a temporal and performance analysis of the process. 
It calculates end-to-end case throughput times (average, min, max), visualizes the duration distribution, and calculates average transition times between consecutive activities to isolate organizational bottlenecks.
Additionally, it filters for 'Declaration REJECTED by MISSING' events to identify which activities immediately precede this automated compliance failure.

Objective (Why we are doing this):
The empirical outputs generated by this script (histograms and CSVs) quantify the process friction and identifying structural inefficiencies in the domestic data.
We can directly compare these programmatic findings against the Celonis visualizations, as well as the International Declarations analysis being conducted in parallel on the shared repository.
"""

import pm4py
import pandas as pd
import matplotlib.pyplot as plt
import os

# Ensure the shared output directory exists
os.makedirs('output', exist_ok=True)

def analyze_domestic_performance(file_path):
    print("Loading event log...")
    # Read the XES file and convert to a standard dataframe
    log = pm4py.read_xes(file_path)
    df = pm4py.convert_to_dataframe(log)

    # Ensure timestamps are standardized datetime objects
    df['time:timestamp'] = pd.to_datetime(df['time:timestamp'], utc=True)

    print("\n--- Step 1: Case Throughput Times ---")
    # Group by case ID to find start and end times
    case_starts = df.groupby('case:concept:name')['time:timestamp'].min()
    case_ends = df.groupby('case:concept:name')['time:timestamp'].max()
    
    # Calculate duration in days
    case_durations = (case_ends - case_starts).dt.total_seconds() / (24 * 3600)

    print(f"Total Domestic Cases: {len(case_durations)}")
    print(f"Average Throughput: {case_durations.mean():.2f} days")
    print(f"Minimum Throughput: {case_durations.min():.2f} days")
    print(f"Maximum Throughput: {case_durations.max():.2f} days")

    print("\n--- Step 2: Analyze Time Distribution ---")
    plt.figure(figsize=(10, 6))
    plt.hist(case_durations, bins=50, color='#4A90E2', edgecolor='black')
    plt.title('Distribution of Case Durations (Domestic Declarations)')
    plt.xlabel('Duration (Days)')
    plt.ylabel('Frequency (Number of Cases)')
    plt.grid(axis='y', alpha=0.75)
    plt.tight_layout()
    plt.savefig('output/domestic_duration_histogram.png')
    print("-> Histogram saved to output/domestic_duration_histogram.png")

    print("\n--- Step 3: Isolate Activity Bottlenecks ---")
    # Sort chronologically within each case to calculate transition times between consecutive activities
    df = df.sort_values(by=['case:concept:name', 'time:timestamp'])
    df['next_activity'] = df.groupby('case:concept:name')['concept:name'].shift(-1)
    df['next_timestamp'] = df.groupby('case:concept:name')['time:timestamp'].shift(-1)
    df['transition_days'] = (df['next_timestamp'] - df['time:timestamp']).dt.total_seconds() / (24 * 3600)

    # Aggregate average transition times
    transitions = df.dropna(subset=['next_activity'])
    bottlenecks = transitions.groupby(['concept:name', 'next_activity'])['transition_days'].agg(['mean', 'max', 'count']).sort_values(by='mean', ascending=False)
    
    print("\nTop 5 Bottleneck Transitions (Average Days):")
    print(bottlenecks.head(5))
    bottlenecks.to_csv('output/domestic_bottlenecks.csv')

    print("\n--- Step 4: Investigate Rejections ---")
    # Isolate instances of the automated rejection marker
    target_rejection = 'Declaration REJECTED by MISSING'
    missing_rejections = df[df['concept:name'] == target_rejection]
    affected_cases = missing_rejections['case:concept:name'].nunique()
    print(f"\nTotal cases containing '{target_rejection}': {affected_cases}")

    # Determine which organizational layer is triggering the missing data rejection
    rejection_predecessors = df[df['next_activity'] == target_rejection]
    predecessor_counts = rejection_predecessors['concept:name'].value_counts()
    print("\nActivities immediately preceding the rejection:")
    print(predecessor_counts)

if __name__ == "__main__":
    # Dynamically locate the file to ensure compatibility across different machines
    # This assumes the script is inside the /src folder and the data is in /Data/raw
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    file_path = os.path.join(project_root, 'Data', 'raw', 'DomesticDeclarations.xes')
    
    analyze_domestic_performance(file_path)